In [8]:
import numpy as np

# 创建不同维度的数组
scalar = np.array(5)
vector = np.array([1,2,3,4,5])
matrix = np.array([[1,2,3],[4,5,6]])

# 查看它们的形状
print("0维标量的形状:", scalar.shape) # 输出: ()
print("1维向量的形状:", vector.shape) # 输出: (5,)
print("2维矩阵的形状:", matrix.shape) # 输出: (2, 3) -> 2行3列


# 创建一个2维数组 (3x4)
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("原始数组:\n", arr)
print("形状:", arr.shape) # (3, 4)

# 索引：获取单个元素
print("获取第2行第3列的元素:", arr[1, 2]) # 输出: 7 (注意: 索引从0开始!)

# 切片：获取子数组
print("获取前两行的所有数据:\n", arr[0:2, :])   # : 代表“所有列”
print("获取第2、3列的所有数据:\n", arr[:, 1:3]) # : 代表“所有行”
print("获取一个2x2的子矩阵:\n", arr[0:2, 1:3])


# 传统方法（笨方法）：用循环
a = [1, 2, 3, 4, 5]
b = []
for i in a:
    b.append(i * 2)
print(b) # [2, 4, 6, 8, 10]

# NumPy方法（向量化）：直接运算
a_np = np.array([1, 2, 3, 4, 5])
b_np = a_np * 2 # 直接把数组乘以2！
print(b_np) # [ 2 4 6 8 10]

# 不仅仅是乘法，所有数学运算都支持向量化
print("加法:", a_np + 5)
print("平方:", a_np ** 2)
print("三角函数:", np.sin(a_np))
print("逻辑判断:", a_np > 3)

0维标量的形状: ()
1维向量的形状: (5,)
2维矩阵的形状: (2, 3)
原始数组:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
形状: (3, 4)
获取第2行第3列的元素: 7
获取前两行的所有数据:
 [[1 2 3 4]
 [5 6 7 8]]
获取第2、3列的所有数据:
 [[ 2  3]
 [ 6  7]
 [10 11]]
获取一个2x2的子矩阵:
 [[2 3]
 [6 7]]
[2, 4, 6, 8, 10]
[ 2  4  6  8 10]
加法: [ 6  7  8  9 10]
平方: [ 1  4  9 16 25]
三角函数: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
逻辑判断: [False False False  True  True]
